services:
  - type: web
    name: yaso-app
    env: node
    plan: free
    buildCommand: "npm run install:all && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "20"
